---
title: "Lab Class 3"
author: "Alejandro Rea"
subtitle: Final Project using Spotify Data to see What Influences Song Skipability
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```


<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library('dplyr')
library('readr')
library('rsample')
# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```



## Question 1

1a) Text response to part a. 

```{r}

track_features <- read_csv("datasets/tf_mini.csv")
session_logs <- read_csv("log_mini.csv")

#renaming track_id to link to track_features dataset
names(session_logs)[names(session_logs) == "track_id_clean"] <- "track_id"


#track and session data together
songs <- merge(track_features, session_logs, by="track_id")

#checking for missing data - no null data
colSums(is.na(songs))

#omitting any NA value rows just in case
songs_clean <- na.omit(songs)

colSums(is.na(songs_clean))

```


1b) Response to part b. 

```{r}

#turning our variables into yes or no in a binary fashion. We could just factor if you fancy that but
songs_clean <- songs_clean %>% 
  mutate(skip_1 = ifelse(skip_1 == "TRUE", 1,0),
          skip_2 = ifelse(skip_2 == "TRUE", 1,0),
          skip_3 = ifelse(skip_3 == "TRUE", 1,0),
          not_skipped = ifelse(not_skipped == "TRUE", 1,0))

```

```{r}

#Since we only care if the song will be counted as a stream we made a new attribute that identifies that. A song will be a stream if it is played for 30 seconds, so if the song is briefly played and skipped, played for a while and skipped, or not skipped at all, it will count as a stream for the artist.

songs_clean$counted_stream <- ifelse((songs_clean$skip_2 == 1 | songs_clean$skip_3 == 1 | songs_clean$not_skipped == 1), 1, 0)


songs_clean <- songs_clean %>% 
  mutate(counted_stream = as_factor(counted_stream),
         mode = as_factor(mode),
         time_signature = as_factor(time_signature),
         hist_user_behavior_is_shuffle = as_factor(hist_user_behavior_is_shuffle),
         premium = as_factor(premium),
         context_type = as_factor(context_type),
         hist_user_behavior_reason_start = as_factor(hist_user_behavior_reason_start),
         hist_user_behavior_reason_end = as_factor(hist_user_behavior_reason_end)
         )


print(songs_clean)

#creating our split
songs_split <- initial_split(songs_clean, prop = 0.75) 

songs_train <- training(songs_split)
songs_test <- testing(songs_split)

```

etc...


## Question 2

2a)my random forest

```{r}

#fit the model on everything but this
rf_fit_songs <- randomForest(counted_stream ~ .,
                        data = songs_train %>% select(-track_id, -session_id, -date, -skip_1, -skip_2, -skip_3, -not_skipped),
                        mtry = 6,
                        ntree = 100,
                        na.action = na.roughfix,
                        importance = TRUE)

print(rf_fit_songs)

```


2b) Response to part b. 


```{r}

plot(rf_fit_songs)

```


## Question 3

Here is only text for question 3. 

If you want to add a hypertext link [you can do so](http://www.chapman.edu)

- If you want to add bullets
  - You
  - Can 
  - Do 
  - It

If you want to add an image [follow this guide](https://stackoverflow.com/questions/25166624/insert-picture-table-in-r-markdown)



