---
title: "LASSO_model"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')
```

```{r setup-2}
# Always print this out before your assignment
sessionInfo()
getwd()
```

```{r setup-3}
# load all your libraries in this chunk 
library('tidyverse')
library('vtable')
library('dplyr')
library('readr')
library('rsample')
library('ggridges')
library('ROSE')
# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 
```

## Data Cleaning
```{r}
track_features <- read_csv("datasets/tf_mini.csv")
session_logs <- read_csv("datasets/log_mini.csv")

#renaming track_id to link to track_features dataset
names(session_logs)[names(session_logs) == "track_id_clean"] <- "track_id"

#track and session data together
songs <- merge(track_features, session_logs, by="track_id")

#omitting any NA value rows just in case
songs_clean <- na.omit(songs)

#turning our variables into yes or no in a binary fashion. We could just factor if you fancy that but
songs_clean <- songs_clean %>% 
  mutate(skip_1 = ifelse(skip_1 == "TRUE", 1,0),
          skip_2 = ifelse(skip_2 == "TRUE", 1,0),
          skip_3 = ifelse(skip_3 == "TRUE", 1,0),
          not_skipped = ifelse(not_skipped == "TRUE", 1,0))

#Since we only care if the song will be counted as a stream we made a new attribute that identifies that. A song will be a stream if it is played for 30 seconds, so if the song is briefly played and skipped, played for a while and skipped, or not skipped at all, it will count as a stream for the artist.

songs_clean$counted_stream <- ifelse((songs_clean$skip_3 == 1 | songs_clean$not_skipped == 1), 1, 0)

songs_clean <- songs_clean %>% select(-track_id, -session_id, -date, -skip_1, -skip_2, -skip_3, -not_skipped, -session_position, -session_length, -context_switch, -no_pause_before_play, -short_pause_before_play, -long_pause_before_play, -hist_user_behavior_n_seekfwd, -hist_user_behavior_n_seekback, -hist_user_behavior_is_shuffle, -hour_of_day, -premium, -context_type, -hist_user_behavior_reason_start, -hist_user_behavior_reason_end, -release_year, -acoustic_vector_0, -acoustic_vector_1, -acoustic_vector_2, -acoustic_vector_3, -acoustic_vector_4, -acoustic_vector_5, -acoustic_vector_6, -acoustic_vector_7)
songs_clean <- songs_clean %>% 
  mutate(counted_stream = as_factor(counted_stream),
         mode = as_factor(mode),
         time_signature = as_factor(time_signature),
         )

```

```{r}
st(songs_clean)
```

```{r}
under <- ovun.sample(counted_stream ~ . , data = songs_clean, method = "under", N = 6292)$data
table(under$counted_stream)

#creating our split
songs_split <- initial_split(under, prop = 0.75) 
songs_train <- training(songs_split)
songs_test <- testing(songs_split)

```

```{r}
#Lasso Model
lasso_mod <- cv.glmnet(counted_stream ~ .,
                        data = songs_train,
                     family = binomial,
                       # note alpha = 1 sets lasso, setting to 1!  
                       alpha = 1)

# Final model with lambda.1se
lasso_1se <- glmnet(counted_stream ~ .,
                   data = songs_train,
                   family = binomial,
                   alpha = 1,
      
                                lambda = lasso_mod$lambda.1se)
```

```{r}
#Lambda 1SE
lambda1se_coef <- coef(lasso_mod, 
     s = lasso_mod$lambda.1se) %>% 
  round(3)

exp(lambda1se_coef)
```

```{r}
#Lambda Penalization
coef(lasso_mod, 
     s = lasso_mod$lambda.min) %>% 
  round(3)
```
```{r}
coef(lasso_mod) %>% 
  round(3)
```
```{r}
lasso_coefs <- tibble(
  `varnames` = rownames(coef(lasso_mod, s = lasso_mod$lambda.1se)),
  `ridge_min` = coef(lasso_mod, s = lasso_mod$lambda.min) %>% 
    round(3) %>% as.matrix() %>% as.data.frame(),
  `ridge_1se` = coef(lasso_mod, s = lasso_mod$lambda.1se) %>% 
    round(3) %>% as.matrix() %>% as.data.frame()
) 
```

```{r}
plot(lasso_mod)
```

```{r}
score_train <- predict(lasso_1se,
                  newdata = songs_train,
                  type = "response")

score_test <- predict(lasso_1se,
                  newdata = songs_test,
                  type = "response")

results_train <- tibble(
  `true_class` = as.numeric(songs_train$counted_stream),
  `prob_event` =  as.numeric(score_train)
)

results_test <- tibble(
  `true_class` = as.numeric(songs_test$counted_stream),
  `prob_event_test` =  as.numeric(score_test),
)

library('plotROC')
p_train <- ggplot(results_train, 
            aes(m = prob_event, d = true_class)) + ggtitle("Training Set") + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.8,0.7,0.5,0.3,0.2,0.1, 0.01, 0.05)) +
  theme_minimal(base_size = 14)
print(p_train)

p_test <- ggplot(results_test, 
            aes(m = prob_event_test, d = true_class)) + ggtitle("Test Set") + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.9,0.8,0.7,0.5,0.3,0.2,0.1, 0.01, 0.05)) +
  theme_minimal(base_size = 14)

print(p_train)
print(p_test)
```

```{r}
auc_train <- calc_auc(p_train)
auc_test <- calc_auc(p_test)

print(auc_train)
```

```{r}
print(auc_test)
```